### ISSUE TITLE
Calling NestJS in getServerSideProps

### ISSUE THREAD

**Issue by ttsirkia** [Skn0tt/nextjs-nestjs-integration-example#10]
What if you had a service providing the random number, would it be possible to call that service easily in getServerSideProps? And the same service in the controller.

In this way you could handle both API calls and loading data for pages by using the same services.

**Comment by Skn0tt** [comment]
It sure is! I've added an example here: [pages/gssp.tsx](https://github.com/Skn0tt/nextjs-nestjs-integration-example/blob/master/src/pages/gssp.tsx)

**Comment by Skn0tt** [comment]
The example injects a Controller, but services can be injected the same way.

**Comment by ttsirkia** [comment]
OK, it's that simple. Thank you very much!
