### ISSUE TITLE
How do I apply graphql to this project?

### ISSUE THREAD

**Issue by clianor** [Skn0tt/nextjs-nestjs-integration-example#16]
How do I apply graphql to this project?

I would like to apply graphql to a project like this.

**Comment by clianor** [comment]
Currently, graphql cannot be used if the example https://docs.nestjs.com/graphql/quick-start is applied to this project.

**Comment by Skn0tt** [comment]
I'm not that familiar with GraphQL. Feel free to provide a PR if you found a way to integrate it!
