### ISSUE TITLE
NestJS can't receive data

### ISSUE THREAD

**Issue by hoangnq3004** [Skn0tt/nextjs-nestjs-integration-example#2]
Hi @Skn0tt !

I want post data to **http://localhost:3000/api/randomNumber** with **'Content-Type': 'application/json'** but NestJS controller can't receiva data.

app.controller.ts
```
    @Post()
    randomNumber(@Body() postDTO) {
        console.log(postDTO)
        return Math.random() * 100;
    }
```
.babelrc
```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "babel-plugin-parameter-decorator"
  ]
}
```
When remove 'Content-Type', NestJS cant receive Body data, but I need JSON.parse it!

**Comment by Skn0tt** [comment]
Hi @hoangnq3004, the provided information is not sufficient for me to efficiently help you. I can have a look if you could provide me with a minimal reproduction case (as in [here](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)).

**Comment by Skn0tt** [comment]
You can have a look at your `bootstrap`-Function though, any body-parser instance that deal with `application/json` can lead your project to hang.

**Comment by hoangnq3004** [comment]
Sorry for my information!

You can see at https://github.com/hoangnq3004/nextjs-nestjs-integration-example

**Comment by Skn0tt** [comment]
Since Next.js already parsed the payloads, the body-parser instance that NestJS enables by default will be passed a non-string body. This causes it to hang.

You'll need to disable body-parser:

```ts
const app = await NestFactory.create(AppModule, { bodyParser: false });
```

**Comment by Skn0tt** [comment]
I've extended the blog post to cover this.

**Comment by hoangnq3004** [comment]
Thank you!
