### ISSUE TITLE
How to release this project to production environment?

### ISSUE THREAD

**Issue by JIAFENG123** [Skn0tt/nextjs-nestjs-integration-example#41]
Hello, I have a problem, that is, this project includes the backend, how do I package it into the production environment?

**Comment by paulorsbrito** [comment]
You'll need to deploy on Vercel, I think.

**Comment by Skn0tt** [comment]
You can deploy this anywhere you'd deploy a Next.js application - Platforms like Vercel or Netlify, as a Docker Container if you use `next start`, or anywhere else.
