### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by elendirx** [Skn0tt/nextjs-nestjs-integration-example#5]
Thank you for this awesome example. I wonder if you succeeded in using NestJs dependency injection. I'm trying to inject some services into a controller, but it ends up being `undefined`. This is just a question, feel free to close this issue. Thanks!

**Comment by elendirx** [comment]
Solved. The problem is that Babel deletes metadata. I was able to make it work thanks to https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata.

**Comment by Skn0tt** [comment]
I always needed to explicitly add decorators for DI to work, great to see this can be fixed :D

**Comment by szabolcs-szilagyi** [comment]
ah this is an awesome fix/tip, was already thinking why do I have to do the DI "manually". Should have read this issue earlier. Think it would be awesome to have this in the sample app. :)

**Comment by Skn0tt** [comment]
> Think it would be awesome to have this in the sample app. :)

Feel free to open a PR!
